---
name: "jellyfin-plugin-kodisyncqueue"
guid: "771e19d6-5385-4caf-b35c-28a0e865cf63"
version: "1.0.0"
nicename: "Kodi Sync Queue"
description: "Sync queues to Kodi"
overview: "Sync queues to Kodi"
category: "General"
artifacts:
  - "Emby.Kodi.SyncQueue.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.0"
